/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_kucro3_XADMA_XADMA */

#ifndef _Included_org_kucro3_XADMA_XADMA
#define _Included_org_kucro3_XADMA_XADMA
#ifdef __cplusplus
extern "C" {
#endif
#undef org_kucro3_XADMA_XADMA_SIZE_BYTE
#define org_kucro3_XADMA_XADMA_SIZE_BYTE 1L
#undef org_kucro3_XADMA_XADMA_SIZE_CHAR
#define org_kucro3_XADMA_XADMA_SIZE_CHAR 2L
#undef org_kucro3_XADMA_XADMA_SIZE_SHORT
#define org_kucro3_XADMA_XADMA_SIZE_SHORT 2L
#undef org_kucro3_XADMA_XADMA_SIZE_INT
#define org_kucro3_XADMA_XADMA_SIZE_INT 4L
#undef org_kucro3_XADMA_XADMA_SIZE_LONG
#define org_kucro3_XADMA_XADMA_SIZE_LONG 8L
#undef org_kucro3_XADMA_XADMA_SIZE_FLOAT
#define org_kucro3_XADMA_XADMA_SIZE_FLOAT 4L
#undef org_kucro3_XADMA_XADMA_SIZE_DOUBLE
#define org_kucro3_XADMA_XADMA_SIZE_DOUBLE 8L
/*
 * Class:     org_kucro3_XADMA_XADMA
 * Method:    getSystemEndian0
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_kucro3_XADMA_XADMA_getSystemEndian0
  (JNIEnv *, jclass);

/*
 * Class:     org_kucro3_XADMA_XADMA
 * Method:    querySize0
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_kucro3_XADMA_XADMA_querySize0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_kucro3_XADMA_XADMA
 * Method:    require0
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_kucro3_XADMA_XADMA_require0
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_kucro3_XADMA_XADMA
 * Method:    acquire0
 * Signature: (Ljava/lang/String;I)J
 */
JNIEXPORT jlong JNICALL Java_org_kucro3_XADMA_XADMA_acquire0
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     org_kucro3_XADMA_XADMA
 * Method:    allocate0
 * Signature: (Ljava/lang/String;I)J
 */
JNIEXPORT jlong JNICALL Java_org_kucro3_XADMA_XADMA_allocate0
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     org_kucro3_XADMA_XADMA
 * Method:    release0
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_kucro3_XADMA_XADMA_release0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_kucro3_XADMA_XADMA
 * Method:    putByte0
 * Signature: (JJB)V
 */
JNIEXPORT void JNICALL Java_org_kucro3_XADMA_XADMA_putByte0
  (JNIEnv *, jclass, jlong, jlong, jbyte);

/*
 * Class:     org_kucro3_XADMA_XADMA
 * Method:    putChar0
 * Signature: (JIJC)V
 */
JNIEXPORT void JNICALL Java_org_kucro3_XADMA_XADMA_putChar0
  (JNIEnv *, jclass, jlong, jint, jlong, jchar);

/*
 * Class:     org_kucro3_XADMA_XADMA
 * Method:    putShort0
 * Signature: (JIJS)V
 */
JNIEXPORT void JNICALL Java_org_kucro3_XADMA_XADMA_putShort0
  (JNIEnv *, jclass, jlong, jint, jlong, jshort);

/*
 * Class:     org_kucro3_XADMA_XADMA
 * Method:    putInt0
 * Signature: (JIJI)V
 */
JNIEXPORT void JNICALL Java_org_kucro3_XADMA_XADMA_putInt0
  (JNIEnv *, jclass, jlong, jint, jlong, jint);

/*
 * Class:     org_kucro3_XADMA_XADMA
 * Method:    putLong0
 * Signature: (JIJJ)V
 */
JNIEXPORT void JNICALL Java_org_kucro3_XADMA_XADMA_putLong0
  (JNIEnv *, jclass, jlong, jint, jlong, jlong);

/*
 * Class:     org_kucro3_XADMA_XADMA
 * Method:    putFloat0
 * Signature: (JIJF)V
 */
JNIEXPORT void JNICALL Java_org_kucro3_XADMA_XADMA_putFloat0
  (JNIEnv *, jclass, jlong, jint, jlong, jfloat);

/*
 * Class:     org_kucro3_XADMA_XADMA
 * Method:    putDouble0
 * Signature: (JIJD)V
 */
JNIEXPORT void JNICALL Java_org_kucro3_XADMA_XADMA_putDouble0
  (JNIEnv *, jclass, jlong, jint, jlong, jdouble);

/*
 * Class:     org_kucro3_XADMA_XADMA
 * Method:    getByte0
 * Signature: (JJ)B
 */
JNIEXPORT jbyte JNICALL Java_org_kucro3_XADMA_XADMA_getByte0
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_kucro3_XADMA_XADMA
 * Method:    getChar0
 * Signature: (JIJ)C
 */
JNIEXPORT jchar JNICALL Java_org_kucro3_XADMA_XADMA_getChar0
  (JNIEnv *, jclass, jlong, jint, jlong);

/*
 * Class:     org_kucro3_XADMA_XADMA
 * Method:    getShort0
 * Signature: (JIJ)S
 */
JNIEXPORT jshort JNICALL Java_org_kucro3_XADMA_XADMA_getShort0
  (JNIEnv *, jclass, jlong, jint, jlong);

/*
 * Class:     org_kucro3_XADMA_XADMA
 * Method:    getInt0
 * Signature: (JIJ)I
 */
JNIEXPORT jint JNICALL Java_org_kucro3_XADMA_XADMA_getInt0
  (JNIEnv *, jclass, jlong, jint, jlong);

/*
 * Class:     org_kucro3_XADMA_XADMA
 * Method:    getLong0
 * Signature: (JIJ)J
 */
JNIEXPORT jlong JNICALL Java_org_kucro3_XADMA_XADMA_getLong0
  (JNIEnv *, jclass, jlong, jint, jlong);

/*
 * Class:     org_kucro3_XADMA_XADMA
 * Method:    getFloat0
 * Signature: (JIJ)F
 */
JNIEXPORT jfloat JNICALL Java_org_kucro3_XADMA_XADMA_getFloat0
  (JNIEnv *, jclass, jlong, jint, jlong);

/*
 * Class:     org_kucro3_XADMA_XADMA
 * Method:    getDouble0
 * Signature: (JIJ)D
 */
JNIEXPORT jdouble JNICALL Java_org_kucro3_XADMA_XADMA_getDouble0
  (JNIEnv *, jclass, jlong, jint, jlong);

#ifdef __cplusplus
}
#endif
#endif
